name: Build nos

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Run tests
        run: make test


  operator:
    needs: test
    permissions:
      contents: write
      packages: write
    uses: nebuly-ai/nos/.github/workflows/.reusable-build.yaml@main
    with:
      component-name: operator
      registry-user: ${{ github.actor }}
    secrets: inherit

  scheduler:
    needs: test
    permissions:
      contents: write
      packages: write
    uses: nebuly-ai/nos/.github/workflows/.reusable-build.yaml@main
    with:
      component-name: scheduler
      registry-user: ${{ github.actor }}
    secrets: inherit

  gpu-partitioner:
    needs: test
    permissions:
      contents: write
      packages: write
    uses: nebuly-ai/nos/.github/workflows/.reusable-build.yaml@main
    with:
      component-name: gpu-partitioner
      registry-user: ${{ github.actor }}
    secrets: inherit

  gpu-agent:
    needs: test
    permissions:
      contents: write
      packages: write
    uses: nebuly-ai/nos/.github/workflows/.reusable-build.yaml@main
    with:
      component-name: gpu-agent
      registry-user: ${{ github.actor }}
    secrets: inherit

  mig-agent:
    needs: test
    permissions:
      contents: write
      packages: write
    uses: nebuly-ai/nos/.github/workflows/.reusable-build.yaml@main
    with:
      component-name: mig-agent
      registry-user: ${{ github.actor }}
    secrets: inherit

  metrics-exporter:
    needs: test
    permissions:
      contents: write
      packages: write
    uses: nebuly-ai/nos/.github/workflows/.reusable-build.yaml@main
    with:
      component-name: metrics-exporter
      registry-user: ${{ github.actor }}
    secrets: inherit

  helm-charts:
    runs-on: ubuntu-22.04
    needs:
      - operator
      - scheduler
      - gpu-partitioner
      - gpu-agent
      - mig-agent
      - metrics-exporter
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Set up Helm
        uses: Azure/setup-helm@v3
        with:
          version: v3.10.3

      - name: Helm login
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.REGISTRY }} -u $ --password-stdin

      - name: Helm push
        run: make helm-push
        env:
          HELM_CHART_REGISTRY: oci://${{ env.REGISTRY }}/${{ github.repository_owner }}/helm-charts
